In [5]:
import numpy as np
import sys
s=range(1000)
print("Size of each element of list in bytes :", sys.getsizeof(s))
print("Size of whole list in bytes :", sys.getsizeof(s)*len(s))

Size of each element of list in bytes : 48
Size of whole list in bytes : 48000


In [9]:
d=np.arange(1000)
print("Size of each element of Numpy array in bytes :", d.itemsize)
print("Size of whole Numpy array in bytes :", d.itemsize*d.size)

Size of each element of Numpy array in bytes : 4
Size of whole Numpy array in bytes : 4000


## array are : faster 😦 (OR) occupy less size 😋 : than list 
### list is dynamic while array has fix length

In [10]:
# Create array
import numpy as np
arr = np.array(24)
print(arr)
print(type(arr))
print(arr.ndim)

24
<class 'numpy.ndarray'>
0


In [11]:
# Create array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
1


In [44]:
# Create array
import numpy as np
arr = np.array([[1,2,3,4,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [24]:
# Create array
import numpy as np
arr = np.array([[[1,2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [35]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print("*********************************")
ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])
print(ar)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
*********************************
[[list([1, 2, 3]) list([4, 5])]
 [list([7, 8]) list([10, 11, 12])]]


<ipython-input-35-a53ce6af24a8>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])


In [42]:
# Create array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[2]+arr[1])
print(arr[7])

3
5


IndexError: index 7 is out of bounds for axis 0 with size 5

In [63]:
# Create array
import numpy as np
arr = np.array([[1,2,3,4,5]])
print("arr[0][2] :",arr[0][2])
print("arr[0,-2] :",arr[0,-2])
print(arr[:2,:4])
print(arr[:1,2])
print(arr[0][1:])

arr[0][2] : 3
arr[0,-2] : 4
[[1 2 3 4]]
[3]
[2 3 4 5]


### slicing : hase etla bracket [] aavse pan coma , ma nai aave 🙄🙄🙄

In [67]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)
print()
ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])
print(ar.shape)

(2, 2, 3)

(2, 2)


<ipython-input-67-dc9eae933ada>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])


In [68]:
arr = np.array([1,2,3])
print(arr.shape)
#Dhayn rakh 🤑

(3,)


In [81]:
arr = np.array([1,2,3,4,5,6,7,8],ndmin=5)
print(arr)
print(arr.shape)
new=arr.reshape(4,2)
print(new)

[[[[[1 2 3 4 5 6 7 8]]]]]
(1, 1, 1, 1, 8)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3,1)
print(newarr)
print("*****************")
newarr=newarr.base
print(newarr)
print("*****************")
newarr=arr.reshape(2,-1)
print(newarr)
print("*****************")
newarr1=arr.reshape(2,3)
print(newarr1)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
*****************
[1 2 3 4 5 6]
*****************
[[1 2 3]
 [4 5 6]]
*****************
[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
arr=np.array([100,68,56,38,72])
for x in arr:
    print(x)

100
68
56
38
72


In [15]:
import numpy as np
arr=np.array([[93,16,22],[2,72,38]])
for x in arr:
    for i in x:
        print(i)

93
16
22
2
72
38


In [19]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for i in x:
        for j in i:
            print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr): # imp).=-> n dimension itteration
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [25]:
import numpy as np
arr=np.array([[93,16,22,90],[2,72,38,99]])
for x in np.nditer(arr[0:1,::2]): 
    print(x)

93
22


### Built in functions

1) Concatenate()  🤝🏻🤝🏻🤝🏻

In [27]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [36]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[7,8],[9,10],[11,12]])
arr=np.concatenate((arr1,arr2))
print(arr) # output also 2 Dimension
print("=================")
arr=np.concatenate((arr1,arr2) , axis=1) #default Value Axis 0
print(arr) 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


### 2) split 😂💔

In [39]:
import numpy as np
arr1=np.array([1,2,3,4])
new =np.array_split(arr1,4)#
print(new)

[array([1]), array([2]), array([3]), array([4])]


In [40]:
import numpy as np
arr1=np.array([1,2,3,4])
new =np.array_split(arr1,3)#
print(new)

[array([1, 2]), array([3]), array([4])]


In [41]:
import numpy as np
arr1=np.array([1,2,3,4])
new =np.array_split(arr1,5)#
print(new)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]


In [48]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6]])#
new =np.array_split(arr1,2)#
print(new)

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


In [51]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
new =np.array_split(arr1,2,axis=1)#
print(new)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [46]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6]])
new =np.array_split(arr1,4)#
print(new)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([], shape=(0, 2), dtype=int32)]


### 3) Where 👈🏻👉🏻👆🏻👇🏻

In [58]:
import numpy as np
arr1=np.array([8,1,5,8,9,6,7,8,8])#
new =np.where(arr1==8)#
print(new)

(array([0, 3, 7, 8], dtype=int64),)


In [90]:
import numpy as np
arr1=np.array([1,5,11,9,6,7,8,8])#
print("Where !!")
new =np.where(arr1==11)#
print(new)
print("Where 10000")# NO error 
print(np.where(arr1==10000))


Where !!
(array([2], dtype=int64),)
Where 10000
(array([], dtype=int64),)


In [61]:
import numpy as np
arr1=np.array([0,5,2,9,6,7,8,8])#
new =np.where(arr1%2==0)#
print(new)

(array([0, 2, 4, 6, 7], dtype=int64),)


In [63]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[4,7]])#
new =np.where(arr1==4)#
print(new) # index hisabe 4 at 1,1  3,0

(array([1, 3], dtype=int64), array([1, 0], dtype=int64))


In [71]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,5]]])#
new =np.where(arr1==5)#
print(new)

(array([0, 0], dtype=int64), array([1, 2], dtype=int64), array([1, 2], dtype=int64))


### 4) sort() 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣

In [82]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(np.sort(arr1))
arr1=np.array(["apple","Banana","cherry"])
print(np.sort(arr1))
arr1=np.array([True,False,True])
print(np.sort(arr1))

[1 2 3 4 5 6 7 8 9]
['Banana' 'apple' 'cherry']
[False  True  True]


In [3]:
import numpy as np
arr1=np.array([[3,4,2],[1,7,3],[9,0,5]])
print("Sort")
print(np.sort(arr1)) 
print()
print("Sort Axis 0")
print(np.sort(arr1,axis=0))
print()
print("Sort Axis 1")  # aama axis = dimension-1 ane sort ans same j aavse 😏😣
print(np.sort(arr1,axis=1))
print()
print("Sort Axis None") 
print(np.sort(arr1,axis=None))

Sort
[[2 3 4]
 [1 3 7]
 [0 5 9]]

Sort Axis 0
[[1 0 2]
 [3 4 3]
 [9 7 5]]

Sort Axis 1
[[2 3 4]
 [1 3 7]
 [0 5 9]]

Sort Axis None
[0 1 2 3 3 4 5 7 9]


In [94]:
import numpy as np
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print("Sort")
print(np.sort(arr1)) 
print()
print("Sort Axis 0")
print(np.sort(arr1,axis=0))
print()
print("Sort Axis 1")
print(np.sort(arr1,axis=1))
print()
print("Sort Axis 2")
print(np.sort(arr1,axis=2))

Sort
[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]

Sort Axis 0
[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]

Sort Axis 1
[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]

Sort Axis 2
[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


## Random
- [0,100) 0 included and 100 excluded

In [140]:
from numpy import random as r
x=r.randint(100) # Number from 0 to 99
print(x)
x=r.randint(10 , 100,size=5) # array of length 5
print(x)
x=r.randint(10 , 100,size=(3,5)) # 3 array of length 5 
print(x)

91
[80 30 99 14 80]
[[97 46 27 40 83]
 [80 18 77 19 74]
 [70 14 32 68 85]]


In [144]:
from numpy import random as r
x=r.rand() # 0 to 0.99
print(x)
x=r.rand(5) # array of len 5
print(x)
x=r.rand(5,3) # 5  array of len 3
print(x)

0.644055261311971
[0.63018808 0.78138179 0.91945891 0.2078414  0.49641183]
[[0.79022775 0.30490011 0.83402036]
 [0.88792653 0.62590516 0.05559107]
 [0.72385993 0.16051207 0.55472009]
 [0.47221795 0.12930113 0.85648375]
 [0.68299134 0.53982867 0.31340441]]


In [165]:
from numpy import random as r
x=r.choice([1,2,3,4,5,6,7]) # any one
print(x)
x=r.choice([1,2,3,4,5,6,7],size=(2)) # any array of 2
print(x)
x=r.choice([1,2,3,4,5,6,7],size=(5,3)) # 7 any array of 2
print(x)

4
[6 5]
[[6 6 3]
 [7 7 5]
 [5 4 5]
 [3 4 1]
 [4 4 5]]


In [170]:
from numpy import random as r
x=r.choice([1,2,3])
print("1.Stone")
print("2.Paper")
print("3.Sissor")
c=int(input("Enter Your Choice"))

if(x==c):
    print("Tie")
elif(x==1 and c==3 || x==2 and c==1 || x==3 and c==2):
    print("Computer Win"):
elif(c>3):
    print("Invalid")
else:
    print("You Win ")
    
### WAITing...

SyntaxError: invalid syntax (<ipython-input-170-c0aef838e6d8>, line 10)

In [185]:
from numpy import random as r
x=r.randint(10)
t=7
while t!=0:
    print()
    print("no of attempt:",t)
    y=int(input("GUESS ??? "))
    if y==x:
        print("Correct")
        print(x)
        break
    
    else :
        print("**** Wrong Ans *****")
        t=t-1
    if t==0 :
        print(x)
    
    


no of attempt: 7
GUESS ??? 2
Correct
2
